CC=gcc

all: 201601
.PHONY: all clean

201601: day-01/solution_pt1.c day-01/solution_pt2.c
	$(CC) -o day-01/solution_pt1.out day-01/solution_pt1.c
	$(CC) -o day-01/solution_pt2.out day-01/solution_pt2.c


clean:
	rm ./**/*.out